### ISSUE TITLE
rollbacks in the temboard database?

### ISSUE THREAD

**Issue by dgiffin** [dalibo/temboard#408]
I'm seeing alerts (nice feature!) for rollbacks in my temboard database, just wondering why?
<img width="1280" alt="temboard-rollback" src="https://user-images.githubusercontent.com/4103061/45939497-80c8bd00-bfc2-11e8-9551-e21dd0348706.png">

**Comment by pgiraud** [comment]
@dgiffin We're very pleased that you enjoy the new alerts feature.
Currently the default setup for the alerts for the rollbacks metrics is `10` and `20` respectively for `warning` and `critical` levels. If it's too low for your needs and you get notified to often you can edit the thresholds.
https://temboard.readthedocs.io/en/latest/temboard-howto-alerting/#probe-status-over-time

But perhaps I misunderstood your question. Are you asking why there are so many rollbacks in the temBoard database?

**Comment by dgiffin** [comment]
The latter - I was wondering why there were rollbacks in the temboard database.

**Comment by pgiraud** [comment]
Fixed via https://github.com/dalibo/temboard/pull/412.

**Comment by debnet** [comment]
I'm curious too, since I restarted the database, temboard starts acting wierdly with rollbacks. Could you provide some information about that?

![image](https://user-images.githubusercontent.com/634832/51756584-a9240d80-20c1-11e9-90f9-c93dbb2c2872.png)

**Comment by dgiffin** [comment]
Currently running v2.2 and I am still seeing a high number of rollbacks in the temboard database:

postgres=# select xact_commit,xact_rollback from pg_stat_database where datname='temboard';
 xact_commit | xact_rollback
-------------+---------------
    78549187 |       4388234
(1 row)

postgres=# \watch
Thu 11 Apr 2019 07:47:13 AM UTC (every 2s)

 xact_commit | xact_rollback
-------------+---------------
    78549297 |       4388240
(1 row)

Thu 11 Apr 2019 07:47:15 AM UTC (every 2s)

 xact_commit | xact_rollback
-------------+---------------
    78549367 |       4388244
(1 row)

Thu 11 Apr 2019 07:47:17 AM UTC (every 2s)

 xact_commit | xact_rollback
-------------+---------------
    78549405 |       4388246
(1 row)

Thu 11 Apr 2019 07:47:19 AM UTC (every 2s)

 xact_commit | xact_rollback
-------------+---------------
    78549405 |       4388246
(1 row)

**Comment by julmon** [comment]
Hello,

ROLLBACKs on temboard database are coming from the ORM (SQLAlchemy), as temboard connections to PostgreSQL repo are not in autocommit mode, each time the ORM needs some information (in read only), it starts a new transaction and rollback it at the end. Please look what I see in PG logs:
```
2019-04-12 11:16:41.239 CEST [29463] LOG:  statement: BEGIN
2019-04-12 11:16:41.239 CEST [29463] LOG:  statement: SELECT t.oid, typarray
	FROM pg_type t JOIN pg_namespace ns
	    ON typnamespace = ns.oid
	WHERE typname = 'hstore';
	
2019-04-12 11:16:41.240 CEST [29463] LOG:  statement: ROLLBACK
```

```
2019-04-12 11:16:41.240 CEST [29463] LOG:  statement: BEGIN
2019-04-12 11:16:41.240 CEST [29463] LOG:  statement: select version()
2019-04-12 11:16:41.240 CEST [29463] LOG:  statement: select current_schema()
2019-04-12 11:16:41.240 CEST [29463] LOG:  statement: show transaction isolation level
2019-04-12 11:16:41.241 CEST [29463] LOG:  statement: SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2019-04-12 11:16:41.241 CEST [29463] LOG:  statement: SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2019-04-12 11:16:41.241 CEST [29463] LOG:  statement: SELECT 'x' AS some_label
2019-04-12 11:16:41.241 CEST [29463] LOG:  statement: ROLLBACK
```

I don't know yet how to change this behavior..

**Comment by julmon** [comment]
There's nothing to do.
